projects:
  locus5:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: uigitjryejbnxnszziult6e5qq
      endpoints:
        prod: >-
          https://yuqkcldcpfhdtezfv5hjb53ftq.appsync-api.us-east-1.amazonaws.com/graphql
