projects:
  locus:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: ktark4vy4fbw5afy6hjnoqlzvu
      endpoints:
        prod: >-
          https://y3u5buzy2ndmrlkbsvapoeytpi.appsync-api.us-east-1.amazonaws.com/graphql
