projects:
  locus:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: 4iaw3w4yn5c5xmbk62vouuupt4
      endpoints:
        prod: >-
          https://cm65nb3gg5a7xci7du74abbaty.appsync-api.us-east-1.amazonaws.com/graphql
