projects:
  locus:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: wv24pwsykrer7bnxroh2quizta
      endpoints:
        prod: >-
          https://xo2av5x2rncjrocutv7r4n4pm4.appsync-api.us-east-1.amazonaws.com/graphql
